### ISSUE TITLE
Hint for centering card ;)

### ISSUE THREAD

**Issue by bwnstck** [CBL-Chattr/Chattr#7]
https://github.com/CBL-Chattr/Chattr/blob/359700f5a65b123bf856eeddac25553aa0af74a6/src/components/card/card.css#L6

Add "margin: 0 auto" to center card 🚀👾

**Comment by BelaM80** [comment]
> https://github.com/CBL-Chattr/Chattr/blob/359700f5a65b123bf856eeddac25553aa0af74a6/src/components/card/card.css#L6
> 
> Add "margin: 0 auto" to center card 🚀👾

But it´s unnecessary, because it´s already centered with grid. 🤷‍♂️

**Comment by bwnstck** [comment]
ah okey :) i looked at the component in mobile version and the content was not centered… at the page it looks nice 👌
